[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
test = "test"
cache_path = "cache"

[rpc_endpoints]
local = "http://127.0.0.1:8545"

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true